Graduate.create(first_name:"Danilo",last_name: "Marichal",cohort: "Shoebill",bio: "Developer",website: "https://www.linkedin.com/in/danilo-marichal-36b714112/",picture:"http://i.imgur.com/WFlcT3t.jpg")
Graduate.create(first_name:"Ali",last_name: "Weinberg",cohort: "Shoebill",bio: "Developer",website: "https://www.linkedin.com/in/ali-weinberg-58751666/",picture:"http://i.imgur.com/XyU0mSI.jpg")
Graduate.create(first_name:"Arthur",last_name: "Lan",cohort: "Shoebill",bio: "Developer",website: "https://www.linkedin.com/in/arturlan/",picture:"http://i.imgur.com/oncXmSL.jpg")
Graduate.create(first_name:"Brooklyne",last_name: "Finni",cohort: "Shoebill",bio: "Developer",website: "https://www.linkedin.com/in/brooklynefinni/",picture:"http://i.imgur.com/y4j3BQE.jpg")
Graduate.create(first_name:"Chelsea",last_name: "Dowling",cohort: "Shoebill",bio: "Developer",website: "https://www.linkedin.com/in/chelseadowling/",picture:"http://i.imgur.com/yqDgO1s.jpg")
Graduate.create(first_name:"Craig",last_name: "Dempsey",cohort: "Shoebill",bio: "Developer",website: "https://www.linkedin.com/in/craiglldempsey/",picture:"http://i.imgur.com/lD7Ozoq.jpg")
Graduate.create(first_name:"Khem",last_name: "Marriott",cohort: "Shoebill",bio: "Developer",website: "https://www.linkedin.com/in/khemmarriott/",picture:"http://i.imgur.com/dK5zdTp.png")
Graduate.create(first_name:"Kristyn",last_name: "Ginski",cohort: "Shoebill",bio: "Developer",website: "https://www.linkedin.com/in/kristynginski/",picture:"http://i.imgur.com/SKNixwh.jpg")
Graduate.create(first_name:"Laura",last_name: "Amaya",cohort: "Shoebill",bio: "Developer",website: "https://www.linkedin.com/in/laura-amaya/",picture:"http://i.imgur.com/Vb3LZca.jpg")
Graduate.create(first_name:"Liz",last_name: "Rodriguez",cohort: "Shoebill",bio: "Developer",website: "https://www.linkedin.com/in/lizdev/",picture:"http://i.imgur.com/hqIpoip.jpg")
Graduate.create(first_name:"Luke",last_name: "Pate",cohort: "Shoebill",bio: "Developer",website: "https://www.linkedin.com/in/lukepate/",picture:"http://i.imgur.com/WG7F4zP.jpg")
Graduate.create(first_name:"Maria",last_name: "Sylla",cohort: "Shoebill",bio: "Developer",website: "https://www.linkedin.com/in/maria-masha-s-7ba26713b/",picture:"http://i.imgur.com/5WiM2Gv.jpg")
Graduate.create(first_name:"Nigel",last_name: "Gardner",cohort: "Shoebill",bio: "Developer",website: "https://www.linkedin.com/in/nmgardner/",picture:"http://i.imgur.com/GjbhAa9.jpg")
Graduate.create(first_name:"Scott",last_name: "Kaplan",cohort: "Shoebill",bio: "Developer",website: "https://www.linkedin.com/in/sikaplan/",picture:"http://i.imgur.com/dMyLBBH.jpg")
Graduate.create(first_name:"Shannon",last_name: "Roberts",cohort: "Shoebill",bio: "Developer",website: "https://www.linkedin.com/in/shannon-shaza-roberts/",picture:"http://i.imgur.com/nkcVNmC.jpg")
Graduate.create(first_name:"Stacey",last_name: "Stewart",cohort: "Shoebill",bio: "Developer",website: "https://www.linkedin.com/in/staceyaliciastewart/",picture:"http://i.imgur.com/wsz5hT6.jpg")
Graduate.create(first_name:"Stefan",last_name: "Hartmann",cohort: "Shoebill",bio: "GA Instructor",website: "https://www.linkedin.com/in/schmartmann00/",picture:"http://i.imgur.com/WEkNs7o.jpg")
Graduate.create(first_name:"Taj",last_name: "English",cohort: "Shoebill",bio: "GA Instructor",website: "https://www.linkedin.com/in/taj-english/",picture:"http://i.imgur.com/NQxbVsF.jpg")
Graduate.create(first_name:"Adam",last_name: "Roberts",cohort: "Shoebill",bio: "Developer",website: "https://www.linkedin.com/in/adamjosephroberts/",picture:"http://i.imgur.com/olE4GAr.jpg")
Graduate.create(first_name:"John",last_name: "Bell",cohort: "Shoebill",bio: "GA Instructor",website: "https://www.linkedin.com/in/johnrbell/",picture:"http://i.imgur.com/fsAzTGd.jpg")
Graduate.create(first_name:"Benjamin",last_name: "De Jesus",cohort: "Shoebill",bio: "Developer",website: "https://www.linkedin.com/in/benjamincdejesus/",picture:"http://i.imgur.com/TvmkWk7.jpg")
Graduate.create(first_name:"Bryan",last_name: "Mytko",cohort: "Shoebill",bio: "GA Instructor",website: "https://www.linkedin.com/in/bryanmytko/",picture:"http://i.imgur.com/CF5Uip9.jpg")
Graduate.create(first_name:"Erin",last_name: "Fox",cohort: "Shoebill",bio: "Developer",website: "https://www.linkedin.com/in/erinkfox/",picture:"http://i.imgur.com/mwuaIn4.jpg")
Graduate.create(first_name:"Jessica",last_name: "Hirsch",cohort: "Shoebill",bio: "Developer",website: "https://www.linkedin.com/in/jessicarhirsch/",picture:"http://i.imgur.com/vZafgBm.jpg")
Graduate.create(first_name:"Mohammad",last_name: "Hunan",cohort: "Shoebill",bio: "Developer",website: "https://www.linkedin.com/in/makermo/",picture:"http://i.imgur.com/u04flTT.jpg")
Graduate.create(first_name:"Raymond",last_name: "Hendricks",cohort: "Shoebill",bio: "Developer",website: "https://www.linkedin.com/in/raymond-hendricks/",picture:"http://i.imgur.com/Cc1ZIj0.jpg")
Graduate.create(first_name:"Yoda",last_name: "The-I",cohort: "Shoebill",bio: "The Help",website: "https://ga-students.slack.com/messages/@yoda/apps/B4C4HBDA6/",picture:"http://i.imgur.com/Pm4L8BU.jpg")
